### ISSUE TITLE
Bring back the `database_driver` parameter

### ISSUE THREAD

**Issue by c33s** [symfony/symfony-standard#1068]
we often develop applications multi database aware, one developer is using mysql the other postgresql, somtimes we even try to support sqlite.

the database driver is something environment specific, so it sould be in the parameters file. also with the new direction in which the new symfony versions are moving, specifically i mean the new [dotenv component][1] and the [remove of the parameters.yaml file in symfony4][2], we should rething the decision of hardcoding the database driver.

it allows better testing if in my CI ifi can set the `database_driver` in the `parameters.yaml` file or via an environment variable.

currently i have to edit every fresh symfony-standard installation and move the `database_driver` in the `parameters.yml` file. also having the environment variable support since [sf2.7][3] and enhaced in [sf3.2][4] makes me belive in readding this back in the `parameters.yml`

personal opinion: even if mysql maybe is the most common database, we shouldn't promote such an inconsistent database. see http://www.cybertec.at/why-favor-postgresql-over-mariadb-mysql/ (i am using postgresql in my php projects since 1999.

related to: https://github.com/symfony/symfony-standard/pull/867 https://github.com/symfony/symfony-standard/pull/722#issuecomment-58039662 https://github.com/symfony/symfony-standard/pull/776

[1]: https://symfony.com/blog/new-in-symfony-3-3-dotenv-component
[2]: http://fabien.potencier.org/symfony4-best-practices.html#Environment_Variables
[3]: https://symfony.com/doc/2.7/configuration/external_parameters.html
[4]: https://symfony.com/doc/3.2/configuration/external_parameters.html

**Comment by c33s** [comment]
maybe somthing for a different issue but does anything speak against having `database_path` also in the `parameters.yml` and autohandle it in the code (like if null use the other dbal parameters)?

```
doctrine:
    dbal:
        driver: '%database_driver%'
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        path: '%database_path%'
```
