### ISSUE TITLE
503 error breaks spooled email sending

### ISSUE THREAD

**Issue by rdimatt** [symfony/symfony-standard#832]
500 error in code breaks spooled emailing of exception, error is this:
```bash
php app/console swiftmailer:spool:send
[2015-07-16 14:51:13] Processing default mailer... 
  [Symfony\Component\Debug\Exception\ContextErrorException]                                                                     
  Catchable Fatal Error: Argument 1 passed to Swift_Transport_AbstractSmtpTransport::send() must implement interface Swift_Mim  
  e_Message, instance of __PHP_Incomplete_Class given, called in /Symfony/vendor/swiftmailer/s  
  wiftmailer/lib/classes/Swift/FileSpool.php on line 169 and defined 
```

If i have an error in my code that throws a 500 exception, i have this set up in `config_prod.yml` so it emails me the error:
```yaml
monolog:
    handlers:
        mail:
            type:         fingers_crossed
            action_level: critical
            handler:      grouped
        grouped:
            type:    group
            members: [streamed, buffered]
        streamed:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        buffered:
            type:    buffer
            handler: swift
        swift:
            type:       swift_mailer
            from_email: noreply@XXXXXXXXX.com
            to_email:   errors@XXXXXXXX.com
            subject:    An Error Occurred!
            level:      debug
```

the spooled email file appears in `app/var/spool/default`, but then when i run `app/console swiftmailer:spool:send`, the error at the top of the issue is reported

Below is a snippet from `composer show`:
```
  swiftmailer/swiftmailer             v5.4.1                        Swiftmailer, free feature-rich PHP mailer
  symfony/assetic-bundle           v2.6.1                        Integrates Assetic into Symfony2
  symfony/monolog-bundle        v2.7.1                        Symfony MonologBundle
  symfony/swiftmailer-bundle     v2.3.8                        Symfony SwiftmailerBundle
  symfony/symfony                     v2.6.10                       The Symfony PHP framework
  monolog/monolog                    1.15.0
```
