### ISSUE TITLE
Log messages contain placeholders instead of the actual values

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-standard#981]
If you create a new Symfony project (`symfony new my_project`), browse it (`http://127.0.0.1:8000`) and open the `var/logs/dev.log` file, you'll see messages like this one:

![log_error](https://cloud.githubusercontent.com/assets/73419/15815534/04d084ba-2bce-11e6-8304-210dbdfc1ec7.png)

The messages contain placeholders (`{route}`, `{event}`, `{listener}`) instead of the actual values.

**Comment by ogizanagi** [comment]
@javiereguiluz : Isn't it expected ? You should configure the `PsrLogMessageProcessor` processor in order to get the placeholders replaced by the variables available in the context automatically:

```yaml
# app/config/services.yml

monolog.processor.psr_log_message_processor:
    class: Monolog\Processor\PsrLogMessageProcessor
    tags:
        - { name: monolog.processor }
```
